### ISSUE TITLE
Add serde and rayon support.

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/atone#1]
Neither of these should be too hard if someone wants to take a stab!

Both should be added behind separate feature flags. Some relevant pointers:

https://github.com/jonhoo/griddle/tree/master/src/external_trait_impls
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/Cargo.toml#L23-L25
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/Cargo.toml#L42-L43
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/Cargo.toml#L53-L54
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/azure-pipelines.yml#L21-L32
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/azure-pipelines.yml#L48
https://github.com/jonhoo/griddle/blob/611daf08542ea28fb3cf33d73cb41e8dedd55bd4/tarpaulin.toml#L2

**Comment by zynaxsoft** [comment]
Hey, I just took a stab at `serde` (#3).

I don't currently have a plan implementing `rayon` though.
